"""empty message

Revision ID: a416deb12d0c
Revises: f6b4307f73db
Create Date: 2022-10-20 21:25:55.639689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a416deb12d0c"
down_revision = "f6b4307f73db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.create_unique_constraint("email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
